### ISSUE TITLE
Couldbt find remote option on windows

### ISSUE THREAD

**Issue by fadii23** [doronz88/pymobiledevice3#809] opened 2024-01-27 04:11 UTC
Usage: python -m pymobiledevice3 [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  activation       activation options
  afc              FileSystem utils
  amfi             amfi options
  apps             application options
  backup2          backup utils
  bonjour          bonjour options
  companion        companion options
  crash            crash report options
  developer        developer options.
  diagnostics      diagnostics options
  lockdown         lockdown options
  mounter          mounter options
  notification     notification options
  pcap             sniff device traffic
  power-assertion  Create a power assertion (wraps...
  processes        processes cli
  profile          profile options
  provision        privision options
  restore          restore options
  springboard      springboard options
  syslog           syslog options
  usbmux           usbmuxd options
  webinspector     webinspector options
  version          get installed package version

C:\Windows\system32>

**Comment by doronz88** [comment] 2024-01-27 12:16
Duplicate of #569

**Closed as completed by doronz88** 2024-01-27 12:16 UTC
