### ISSUE TITLE
python3 -m pymobiledevice3 usbmux list can not get iphone info (IOS17) via wifi

### ISSUE THREAD

**Issue by HaoWShi** [doronz88/pymobiledevice3#618] opened 2023-10-18 03:38 UTC
**Test environment**
- Host OS version. Mac , MacOS Sonoma 14.0
- Target device model and iOS version.Iphone14 Pro ,IOS17.0.3

**Describe the bug**
pymobiledevice3 version : 2.16.0
I can not get my deviceinfo by command 'python3 -m pymobiledevice3 usbmux list'  when I make Mac and Iphone connect to the same wifi, and config connect via network in xcode
But every thing work normal when I make mac and iphone connect by usb

**To Reproduce**
1、make mac and iphone connect via usb
2、open xcode, and choose Window/Devices and Simulators, to enable connect via network(in fact, the config is enable by defualt) 
3、make mac and iphone connect to same wifi
4、disconnect the usb bwtween mac and iphone
5、xcode can show the iphone info after usb is disconnect
6、open terminal, and run the command ''python3 -m pymobiledevice3 usbmux list'

**Expected behavior**
I can get my deviceinfo by command 'pymobiledevice3 usbmux list' when Mac and iphone connect to same wifi

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

**Comment by doronz88** [comment] 2023-10-18 05:17
the correct way to enable lockdownd wifi is (while on wifi):
```shell
pymobiledevice3 lockdown wifi-connection on
```
that will make the `usbmux list` show devices from network.

however, the remoted wifi isn't supported

**Comment by doronz88** [comment] 2023-11-03 06:43
The `remoted` wifi-connections is a duplicate of #634

**Closed as completed by doronz88** 2023-11-03 06:43 UTC

**Comment by ltDino** [comment] 2023-12-11 02:36
> The `remoted` wifi-connections is a duplicate of #634

but when i use
`sudo python3 -m pymobiledevice3 remote start-tunnel`
it not works, `ERROR Device is not connected`
