### ISSUE TITLE
Permission Error occurs when `developer_disk_image_dir.mkdir` in `auto_mount_developer` 

### ISSUE THREAD

**Issue by joonyoungP** [doronz88/pymobiledevice3#1114] opened 2024-07-08 07:41 UTC
**Test environment**
- MAC OS Version : 14.4.1
- Xcode verison : 15.4
- iOS version : iOS 15.1
- pmd3 version : 4.11.4

**Describe the bug**
i've tried auto_mount with my iPhone but it failed to mkdir because of `PermissionError`
it seems `developer_disk_image_dir.mkdir` makes dir in root user 
but `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport` can't make dir with root user

**To Reproduce**
```    
self.lockdown = create_using_usbmux(self.udid)
await auto_mount(self.lockdown)
```

**result**
```
  File "/opt/apps/testex_appium_api/venv/lib/python3.9/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 360, in auto_mount
    auto_mount_developer(lockdown, xcode=xcode, version=version)
  File "/opt/apps/testex_appium_api/venv/lib/python3.9/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 331, in auto_mount_developer
    developer_disk_image_dir.mkdir(exist_ok=True, parents=True)
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 1] Operation not permitted: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/15.1'
```

**DeviceSupport** 
```
embian@JoonyoungParkui-Macmini DeviceSupport % pwd
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
embian@JoonyoungParkui-Macmini DeviceSupport % ls -al
total 0
drwxrwxr-x  28 embian  staff  896  4  3  2023 .
drwxr-xr-x  10 embian  staff  320  6 13 11:47 ..
drwxrwxr-x   4 embian  staff  128  6 13 11:45 12.0
drwxrwxr-x   4 embian  staff  128  6 13 11:45 12.1
drwxrwxr-x   4 embian  staff  128  6 13 11:45 12.2
drwxrwxr-x   4 embian  staff  128  6 13 11:45 12.3
drwxrwxr-x   4 embian  staff  128  6 13 11:45 12.4
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.0
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.1
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.2
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.3
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.4
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.5
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.6
drwxrwxr-x   4 embian  staff  128  6 13 11:45 13.7
drwxrwxr-x   4 embian  staff  128  6 13 11:45 14.0
drwxrwxr-x   4 embian  staff  128  6 13 11:45 14.1
drwxrwxr-x   4 embian  staff  128  6 13 11:45 14.2
drwxrwxr-x   4 embian  staff  128  6 13 11:45 14.3
drwxrwxr-x   4 embian  staff  128  6 13 11:45 14.4
drwxrwxr-x   4 embian  staff  128  6 13 11:45 14.5
drwxrwxr-x   4 embian  staff  128  6 13 11:45 15.0
drwxrwxr-x   4 embian  staff  128  6 13 11:45 15.2
drwxrwxr-x   4 embian  staff  128  6 13 11:45 15.4
drwxrwxr-x   4 embian  staff  128  6 13 11:45 15.5
drwxrwxr-x   4 embian  staff  128  6 13 11:45 16.0
drwxrwxr-x   4 embian  staff  128  6 13 11:45 16.1
drwxr-xr-x   4 embian  staff  128  6 13 11:45 16.4
```

**Comment by doronz88** [comment] 2024-07-08 09:22
Did you try to chmod the dir?

**Comment by joonyoungP** [comment] 2024-07-08 09:59
> Did you try to chmod the dir?

you're asking for chmod dir after mkdir Developerdisk? or `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport`?

**Comment by doronz88** [comment] 2024-07-08 10:43
Yes. As the error suggests, you have permissions error

**Comment by joonyoungP** [comment] 2024-07-09 05:50
same issue occured after I `chmod 777 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport` and `chown root:staff`

**Comment by doronz88** [comment] 2024-07-09 09:32
Well, what would you expect pymobile to do if you're having permissions problems?
Also a duplicate of:
https://github.com/doronz88/pymobiledevice3/issues/1074

**Closed as completed by doronz88** 2024-07-09 09:32 UTC
