### ISSUE TITLE
Start tunneld error:  ValueError: 'fe80::1051:4881:cee3:2dc5%en0' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by codematrixer** [doronz88/pymobiledevice3#1035] opened 2024-05-27 11:32 UTC
**Test environment**
- macOS
- IOS 17.2.1
- python 3.8
- pymobiledevice3  4.8.5
- zeroconf 0.132.2

when I execute this command : `sudo python3 -m pymobiledevice3 remote tunneld`

Error occurs：

2024-05-27 19:35:23 marxer.local pymobiledevice3.tunneld[73058] ERROR Error raised from: handle-new-potential-usb-cdc-ncm-interface-task-fe80::182e:2625:61f:a453%en12: Traceback (most recent call last):
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/pymobiledevice3/tunneld.py", line 243, in handle_new_potential_usb_cdc_ncm_interface_task
    answers = await browse(REMOTED_SERVICE_NAMES, [ip])
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 83, in browse
    bonjour_queries = [query_bonjour(service_names, adapter) for adapter in ips]
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 83, in <listcomp>
    bonjour_queries = [query_bonjour(service_names, adapter) for adapter in ips]
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/pymobiledevice3/bonjour.py", line 74, in query_bonjour
    aiozc = AsyncZeroconf(interfaces=[ip])
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/zeroconf/asyncio.py", line 166, in __init__
    self.zeroconf = zc or Zeroconf(
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/zeroconf/_core.py", line 172, in __init__
    ip_version = autodetect_ip_version(interfaces)
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 408, in autodetect_ip_version
    has_v6 = any(
  File "/Users/charlichen/develop/open_sources/tidevice3/venv/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 409, in <genexpr>
    isinstance(i, int) or (isinstance(i, str) and ipaddress.ip_address(i).version == 6)
  File "/usr/local/Cellar/python@3.8/3.8.18_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'fe80::182e:2625:61f:a453%en12' does not appear to be an IPv4 or IPv6 address

**Comment by doronz88** [comment] 2024-05-27 15:43
Please verify if #1036 solves the issue

**Comment by codematrixer** [comment] 2024-05-28 02:48
> Please verify if #1036 solves the issue

 No errors occurred, but the IPv6 address is not being displayed. When I open http://127.0.0.1:49151, it returns {}.

**Comment by doronz88** [comment] 2024-05-28 05:09
What macOS are you using?

**Comment by codematrixer** [comment] 2024-05-28 05:14
> What macOS are you using?

M2 mocOS 14.2.1 (23C71)

But when I switched to Python 3.9, the problem was solved.

**Comment by doronz88** [comment] 2024-05-28 05:22
Managed to reproduce it. Looks like Python3.8 (and probably other older versions) has problems resolving IPv6 link-local addresses in general so nothing we can do about it.

**Comment by doronz88** [comment] 2024-05-28 05:28
Updated the PR with a more informative error

**Closed as completed** 2024-05-28 05:38 UTC
