### ISSUE TITLE
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY') When Running start-quic-tunnel

### ISSUE THREAD

**Issue by MK7daniel** [doronz88/pymobiledevice3#884] opened 2024-03-12 23:33 UTC
Test Environment:

Host OS Version: 
MacBook Pro M2 2022, macOS 14.4 (23E214)

Target Device Model and OS Version: 
iPad Pro 12.9 inch 5th Generation, iPadOS 17.4 (21E219)

Bug Description:
Encountering a KeyError related to handling the public key while attempting to execute the start-quic-tunnel command using pymobiledevice3.

Steps to Reproduce:

1. Open Terminal.
2. Execute the command `sudo python3 -m pymobiledevice3 remote start-quic-tunnel`.
3. Observe the error message.

Expected Behavior:
The QUIC tunnel starts successfully without any errors.

Logs:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  ...
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')
```

Additional Context:
The error indicates an issue with the handling of the public key during the pairing process with the target device.

Thank you for allowing me to report this issue. I look forward to a response and appreciate any support that can help resolve it.

**Comment by doronz88** [comment] 2024-03-13 06:04
Duplicate of #879

**Closed as completed by doronz88** 2024-03-13 06:04 UTC

**Comment by MK7daniel** [comment] 2024-03-14 20:54
I don't use a Apple TV.
